### ISSUE TITLE
Problems in the flatzinc specs

### ISSUE THREAD

**Issue by sthiele** [MiniZinc/minizinc-doc#25]
While working on a flatzinc parser, I found two problems within the [flatzinc specs](https://www.minizinc.org/doc-2.4.3/en/fzn-spec.html#specification-of-flatzinc).
In my code I made some changes to the grammar which should probably go back to the specs.

# Problem 1

The specs define `ann-expr` as follows (which does not match how `ann-expr` are used in the minizinc-benchmarks):

```text
<ann-expr>   ::= <expr>
              | <annotation>
```

On the other hand the parser skeleton provided by Guido implements `annotation_expr` like that:

```yaac
annotation_expr :
      ann_non_array_expr
    | '[' annotation_list ']'

ann_non_array_expr :
      FZ_BOOL_LIT
    | FZ_INT_LIT
    | FZ_FLOAT_LIT
    | set_literal
    | var_par_id /* variable, possibly array */
    | var_par_id '[' ann_non_array_expr ']' /* array access */
    | FZ_STRING_LIT
```

## FIX

- I changed the grammar rules for `ann_expr` to reflect real cases similar to the flatzinc_skeleton file.
  It seems the string-literal is missing from the specs

  - old ann-expr
    ```
    <ann_expr> ::= <expr> | <annotation>
    ```
  - new ann-expr
    ```
    <ann_expr> ::= <expr>
                 | <string_literal>
                 | "[" <annotation> "," ... "]"
    ```

# Problem 2

I moved `"var set of int"` from `basic-pred-param` to `basic-var-type`, because the old version caused problems with the following case where `"var set of int"` is used as variable type.

```text
array [1..1] of var set of int: sets:: output_array([1..1]) = [X_INTRODUCED_0_];
                ^            ^
                |____________|
```
Another valid example with `"var set of int"` used in the place of variable type is:

```minizinc
var set of int: g = { 1, 2, 3};
var float: objective;
solve minimize objective;
```

The grammar rules for `basic-var-type` and `basic-pred-param-type` now look like this.
`"set of int"` is covered by `<basic-par-type>`

```text
<basic-var-type> ::= "var" <basic-par-type>
                   | "var" <int-literal> ".." <int-literal>
                   | "var" "{" <int-literal> "," ... "}"
                   | "var" <float-literal> ".." <float-literal>
                   | "var" "set" "of" <int-literal> ".." <int-literal>
                   | "var" "set" "of" "{" [ <int-literal> "," ... ] "}"

<basic-pred-param-type> ::= <basic-par-type>
                          | <basic-var-type>
                          | <int-literal> ".." <int-literal>
                          | <float-literal> ".." <float-literal>
                          | "{" <int-literal> "," ... "}"
                          | "set" "of" <int-literal> .. <int-literal>
                          | "set" "of" "{" [  <int-literal> "," ... ] "}"
```

**Comment by guidotack** [comment]
Thanks! We'll make sure this gets fixed in the next release.
