### ISSUE TITLE
Broken links

### ISSUE THREAD

**Issue by pierfle** [MiniZinc/minizinc-doc#4]
The "More..." links at https://www.minizinc.org/doc-latest/en/lib-globals.html are broken; for example, the first one, for alldifferent, goes (under 2.2.3) to the non-existing https://github.com/MiniZinc/libminizinc/blob/2.2.3/share/minizinc/std//all_different.mzn#L7-L8 .

**Comment by guidotack** [comment]
The git tags for releases 2.2.0-2.2.3 were missing on GitHub again, I've restored them and the links should work again now.
