### ISSUE TITLE
Reference manual entry for x ^ y is unclear

### ISSUE THREAD

**Issue by PerMildner** [MiniZinc/minizinc-doc#6]
The reference page for `x ^ y` just describes it as "_Return x ^ y_".
However, `^` is not a standard mathematical notation, and has no standard meaning in programming languages since it means different things in [different programming languages](https://en.wikipedia.org/wiki/Exponentiation).

So, from looking at the reference page there is no way to know what `x ^ y` means.

**Comment by guidotack** [comment]
Thanks, this is now fixed on the develop branch and the fix will be part of the next release.
