### ISSUE TITLE
The reference page for diff is incorrectly formatted

### ISSUE THREAD

**Issue by PerMildner** [MiniZinc/minizinc-doc#8]
The [reference page](https://www.minizinc.org/doc-2.2.3/en/lib-builtins.html#set-operations) says "_Return the set difference of sets x \&minus; y_" (I.e., literally "&" followed by "minus" followed by ";"). The [source](https://github.com/MiniZinc/libminizinc/blob/2.2.3/share/minizinc/std//builtins.mzn#L714-L725) uses "\&minus;" which also seems strange, since a specific set-minus symbol (like "&setminus;" \&setminus;) seems more appropriate if available.

**Comment by guidotack** [comment]
Thanks, this is now fixed in the repository and the fix will be part of the next release.
